### ISSUE TITLE
Macro $SERVICEDOWNTIME$ not working

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-engine#24] opened 2015-08-26 15:37 UTC
Hi,

I have command that should return how long service has been down with an email, but it always returns 0. With hosts the $HOSTDOWNTIME$ work very well. I am using Centurion 2.5.4.

**Comment by ganoze** [comment] 2015-09-02 06:57
Which version of Centreon Engine are you using ? I've just tested with 1.4.14 and the $SERVICEDOWNTIME$ macro seems to work fine. Could you provide precise steps of how to reproduce your issue ?

**Comment by kadrika** [comment] 2015-09-02 13:56
Hi,
We are using the same version. The command I am using is like this:
/bin/sh -c '/usr/bin/printf "%b" "***** Monitoring *****\n\nNotification Type: $NOTIFICATIONTYPE$\n\nService: $SERVICEDESC$\nHost: $HOSTALIAS$\nAddress: $HOSTADDRESS$\nState: $SERVICESTATE$\nCustomer: $HOSTGROUPALIAS$ \n\nDate/Time: $DATE$ Additional Info : $SERVICEOUTPUT$\nTime down: $SERVICEDOWNTIME$" | /bin/mail -s "** $NOTIFICATIONTYPE$ alert - $HOSTALIAS$/$SERVICEDESC$ is $SERVICESTATE$ **" $CONTACTEMAIL$'

**Comment by ganoze** [comment] 2015-09-03 07:00
This seems to be a notification command for services. All right. However you're using the $SERVICEDOWNTIME$ macro which indicates the current depth of downtime (how much downtimes are currently started for this service). And downtimes disable notifications.

So I guess this is the normal behavior.

What do you think about it ? Is there anything that I understand wrong ?

**Comment by kadrika** [comment] 2015-09-03 07:20
If the $SERVICEDOWNTIME$ is only for downtime, then I have 2 questions.
1. if I configure $HOSTDOWNTIME$ to notification it shows me nicely how much time this host has been down. Why do $SERVICEDOWNTIME$ and $HOSTDOWNTIME$ work differently?
2. If I need to get information with notification how much time has service been down or in warning state, then what macro should I use?

**Comment by ganoze** [comment] 2015-09-03 07:41
1. For me $HOSTDOWNTIME$ behave the same way than $SERVICEDOWNTIME$ (during my tests I tested it also).
2. As per the documentation you should use $SERVICEDURATION$ or $SERVICEDURATIONSEC$. The complete list of standard macros is available at https://documentation.centreon.com/docs/centreon-engine/en/latest/user/configuration/basics/standard_macros.html

**Comment by kadrika** [comment] 2015-09-03 08:12
Thanks that $SERVICEDURATION$ works great!

**Comment by ganoze** [comment] 2015-09-03 08:19
Perfect ! Therefore I'm closing the ticket.

**Closed by ganoze** 2015-09-03 08:19 UTC
Labels: bug
