### ISSUE TITLE
Recovery notifications not more send

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-engine#14] opened 2015-05-04 15:32 UTC
We use Centreon 2.6.0 with Centreon Engine 2.4.12 and Centreon Broker 2.8.2 and it seem's that after the last updates the recovery notifications are not more sendet. I checked out the hole configuration:
- service template: recovery notification is ok
- service configuration: recovery notification is ok
- user configuration: recovery notification is ok

Every other type of notification (warning, error) is send correctly. Is this a issue?

**Comment by joschi99** [comment] 2015-05-04 18:47
I downgraded the Centreon Engine from 2.4.12 to 2.4.11 and now the recovery notification works fine.

**Comment by ganoze** [comment] 2015-05-05 06:54
You got likely trapped in a bug fixed in the 1.4.12 release. This bug caused recovery notifications to be sent for a node (host or service) even if no other notification was sent for this specific node. This was not the intended behavior as explained [here] (https://documentation.centreon.com/docs/centreon-engine/en/latest/user/configuration/basics/notifications.html) .

I'm marking this issue as *wontfix* because this is likely what will happen. However if this is a real bug and no recovery notification is sent *at all* for some nodes, feel free to reopen this ticket and provide the configuration of the node and associated contact that should receive notifications and I'll look into it further.

**Closed** 2015-05-05 07:05 UTC
Labels: bug, wontfix

**Comment by joschi99** [comment] 2015-05-05 14:30
Probably we have some missunderstanding. With release 1.4.12 no recovery notifications are more send. All other notifications like warning, critical ecc. are working very well. So I don't think that I have a mismatch in the configuration,
So please reopen the case and i will provide to you all the configuration files that you need. Please tell me how I can upload the config files because here on github only png, gif or jpg are allowed.

**Comment by cortex93** [comment] 2015-05-11 18:26
Its really a bug, not an configuration problem.
I have exactly the same problem with many test. (Contact, Notification type with service or template etc).

https://forum.centreon.com/showthread.php/16621-No-recovery-notifications-after-update-to-Centreon-2-6-0

You are not alone :).

**Comment by joschi99** [comment] 2015-05-11 20:23
Hi Cortex93,
I opend a new [bug #16](https://github.com/centreon/centreon-engine/issues/16) for this because they closed this bug. Can you post your info on the new bug?
Thx
