### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by dmagniez** [centreon/centreon-engine#88] opened 2017-09-20 10:18 UTC
Hello,

I upgraded centengine from 1.6.2 to 1.8.0, and since, centengine crash with segfault

[ 3407.181066] centengine[7412]: segfault at 21 ip 0000000000000021 sp 00007ffe79dab6e8 error 14 in centengine[400000+3dd000]

I reinstalled clib to be sure.
I suspect centengine to work well with default config.

logs give no error, and stop at INITIAL SERVICE STATE
[1505898127] [8051] INITIAL SERVICE STATE: MGMT;HP-Hardware-Health;OK;HARD;1;
[1505898127] [8051] INITIAL SERVICE STATE: MGMT;Ping;OK;HARD;1;

What do you need for futher investigation ?

here is my centengine.cfg
`
cfg_file=/usr/local/centreon-engine/etc/hostTemplates.cfg
cfg_file=/usr/local/centreon-engine/etc/hosts.cfg
cfg_file=/usr/local/centreon-engine/etc/serviceTemplates.cfg
cfg_file=/usr/local/centreon-engine/etc/services.cfg
cfg_file=/usr/local/centreon-engine/etc/commands.cfg
cfg_file=/usr/local/centreon-engine/etc/contactgroups.cfg
cfg_file=/usr/local/centreon-engine/etc/contacts.cfg
cfg_file=/usr/local/centreon-engine/etc/hostgroups.cfg
cfg_file=/usr/local/centreon-engine/etc/servicegroups.cfg
cfg_file=/usr/local/centreon-engine/etc/timeperiods.cfg
cfg_file=/usr/local/centreon-engine/etc/escalations.cfg
cfg_file=/usr/local/centreon-engine/etc/dependencies.cfg
cfg_file=/usr/local/centreon-engine/etc/connectors.cfg
cfg_file=/usr/local/centreon-engine/etc/meta_commands.cfg
cfg_file=/usr/local/centreon-engine/etc/meta_timeperiod.cfg
cfg_file=/usr/local/centreon-engine/etc/meta_host.cfg
cfg_file=/usr/local/centreon-engine/etc/meta_services.cfg
broker_module=/usr/local/centreon-engine/lib/centreon-engine/externalcmd.so
broker_module=/usr/local/centreon-broker/lib/cbmod.so /usr/local/centreon-broker/etc/poller-1.xml
interval_length=60
resource_file=/usr/local/centreon-engine/etc/resource.cfg
log_file=/var/log/centreon-engine/centengine.log
status_file=/var/log/centreon-engine/status.dat
use_check_result_path=0
status_update_interval=30
external_command_buffer_slots=4096
command_check_interval=1s
command_file=/var/lib/centreon-engine/rw/centengine.cmd
state_retention_file=/var/log/centreon-engine/retention.dat
retention_update_interval=60
sleep_time=0.2
service_inter_check_delay_method=s
host_inter_check_delay_method=s
service_interleave_factor=2
max_concurrent_checks=400
max_service_check_spread=5
max_host_check_spread=5
check_result_reaper_frequency=5
max_check_result_reaper_time=10
low_service_flap_threshold=25.0
high_service_flap_threshold=50.0
low_host_flap_threshold=25.0
high_host_flap_threshold=50.0
service_check_timeout=60
host_check_timeout=10
event_handler_timeout=30
notification_timeout=30
ocsp_timeout=5
ochp_timeout=5
perfdata_timeout=5
date_format=euro
illegal_object_name_chars=~!$%^&*"|<>?,()=
illegal_macro_output_chars=~$^&"|'<>
admin_email=admin@localhost
admin_pager=admin
event_broker_options=-1
translate_passive_host_checks=2
passive_host_checks_are_soft=2
debug_file=/var/log/centreon-engine/centengine.debug
debug_level=-1
debug_verbosity=2
max_debug_file_size=1000000000
log_pid=1
enable_notifications=1
execute_service_checks=1
accept_passive_service_checks=1
execute_host_checks=1
accept_passive_host_checks=1
enable_event_handlers=1
check_external_commands=1
use_retained_program_state=1
use_retained_scheduling_info=1
use_syslog=0
log_notifications=1
log_service_retries=1
log_host_retries=1
log_event_handlers=1
log_initial_states=1
log_external_commands=1
log_passive_checks=0
auto_reschedule_checks=0
use_aggressive_host_checking=0
soft_state_dependencies=0
obsess_over_services=0
process_performance_data=0
check_for_orphaned_services=0
check_for_orphaned_hosts=0
enable_flap_detection=0
enable_predictive_host_dependency_checks=0
enable_predictive_service_dependency_checks=0
use_large_installation_tweaks=1
`

**Comment by ganoze** [comment] 2017-09-20 10:45
Could you send us your entire configuration directory (/etc/centreon-engine) ?

**Comment by dmagniez** [comment] 2017-09-20 19:20
[centengine.zip](https://github.com/centreon/centreon-engine/files/1318947/centengine.zip)

Here are the result of centengine -D do you need more ?

**Comment by ganoze** [comment] 2017-09-21 06:58
Thank you very much ! Unfortunately it seems that the configuration directory is not complete. Could you zip it yourself and send it to me ?

**Comment by dmagniez** [comment] 2017-09-21 08:11
[etc.zip](https://github.com/centreon/centreon-engine/files/1320394/etc.zip)

Here is the full content of my centengine etc

I have anonymised some parts, taking care to not remove any special char ;)

**Comment by dmagniez** [comment] 2017-10-02 10:05
hello, any news on it ?

**Comment by ganoze** [comment] 2017-10-06 09:24
Unfortunately I was not able to reproduce your issue. Configuration parsing fails with the following error.

`[1507281759] [463] Error: Cannot merge object of type 'SOLIDD-IPMI-DELL'`

**Comment by dmagniez** [comment] 2017-10-06 15:10
How can I help you ? Can I give you access to my server ? Do I need to make a conf dump with private info, and send it to you ?

**Comment by ganoze** [comment] 2017-10-09 08:31
Your configuration files with all information would be very much appreciated. You can contact me at mkermagoret@centreon.com

**Comment by ganoze** [comment] 2017-10-13 08:23
@dmagniez You sent me your configuration files off-thread. However I am not able to reproduce your issue and it seems that you are using a custom setup (compiled from sources ?).

Could you try to reproduce this issue using the packages that we provide (https://documentation.centreon.com/docs/centreon/en/2.8.x/installation/from_packages.html) ?

**Comment by dmagniez** [comment] 2017-10-13 14:26
@ganoze I'm using source package, because I'm on debian.unfortunately, your package can't be used on debian... How can we progress about that ?

**Comment by ganoze** [comment] 2017-10-18 07:50
Unfortunately there's not much I can do for you. Your installation does not seem standard and many parameters can influence how Centreon Engine reacts.

So unless you are willing to try our RPMs or find the bug origin yourself, this ticket will likely be closed because of irreproducibility.

**Comment by dmagniez** [comment] 2017-11-04 08:02
centengine works fine just after compilation, with initial config files. If I export my config file and reload centengine, it works well, if I restart centengine, it crash. I'm trying to install previous version.

**Comment by dmagniez** [comment] 2017-11-14 16:30
I digged into this issue, it appear that centreon-engine crash with cbmod.so when I upgraded centreon-broker from 3.0.2 to 3.0.10. I didn't find any informations about an incompatibility issue in release notes of both.

I edited centengine.cfg to comment the line with cbmod.so loading, Starting instantly.

how can I help to correct this issue ?
for the moment, I'm downgrading to centreon-broker 3.0.2

**Comment by ganoze** [comment] 2018-02-02 14:42
With the latest bugfix releases of both Centreon Engine and Centreon Broker there should be no incompatibility. However as I said, your installation being non-standard, there's no way I can help you.

The sole way to get this fixed would be that you either try RPM versions of the incriminated software or use gdb to find the bug yourself.

**Comment by SylvestreG** [comment] 2019-10-21 19:30
Hi, a lot of improvements has been done since this issue.

I will close this issue, feel free to re-open this issue if the problem still happens, we will have a look at it.

Best regards,

**Closed by SylvestreG** 2019-10-21 19:30 UTC
Labels: Kind/Bug, Status/Need more information
