### ISSUE TITLE
Downtime not working for hostgroups (1200 hosts)

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon-engine#21] opened 2015-07-09 13:18 UTC
Hi,

I programmed a downtime on a hostgroup, which contains 1200 hosts.
Downtime not working.

In /var/log/centreon/centcore.log, I see it's programmed, but in /var/log/centreon-engine/centengine.log it does not work.

I tested with an other hostgroup (5 hosts), there is no bug.
It's limited ?

Regards

**Comment by ganoze** [comment] 2015-09-01 11:44
I unfortunately was not able to reproduce this issue. With a 1000 member host group everything works fine, all downtimes are started and hosts properly flagged as in downtime.

Could you provide more information on your issue ? Are only some hosts set in downtime or none of them ? Do you use any special method for setting the downtime ?

**Comment by Marc--** [comment] 2015-09-01 13:44
Hi,

The downtime is scheduled using "Configuration -> Hosts -> Downtimes".

It concern 2 hostgroups : 1213 + 472 = 1685 Hosts

The Downtime has 3 time periods: 
Sat-Sun (0h00 - 23h59)
Mon-Fri (0h00 - 08h00)
Mon-Fri (18h00 - 23h59)

Every host has 1 service.

I've just tried with a smaller hostgroup (472 hosts). I cant see 944 lines in "/var/log/centreon/centcore.log" :
[1441109404] SCHEDULE_HOST_DOWNTIME;FR02096VWA;1441109700;1441110600;1;0;0;Downtime cycle;[Downtime cycle #31]
[1441109404] SCHEDULE_HOST_SVC_DOWNTIME;FR02096VWA;1441109700;1441110600;1;0;0;Downtime cycle;[Downtime cycle #31]


Strange thing, i can see this in : /var/log/centreon-engine/centengine.log

[...]
[1441109107] [26262] EXTERNAL COMMAND: SCHEDULE_HOST_SVC_DOWNTIME;FR02094VWA;1441109700;1441110600;1;0;0;Downtime cycle;[Downtime cycle #31]
[1441109107] [26262] Warning: Unrecognized external command -> SCHEDULE_HOST

No hosts are set in downtime.


I've also tested the same Downtime on a group of 2 hosts, and the downtimes are OK.

Regards,
Marc

**Comment by ganoze** [comment] 2015-09-03 11:52
After discussing with @bmareau it seems that the downtime scheduling issue is likely to come from centcore.

@julienmathis does the following errors ring any bell to you ?

    2015-07-03 17:51:03 - MySQL error: MySQL server has gone away (caller: centreon::script::centcore:/usr/lib/perl5/vendor_perl/5.8.8/centreon/script/centcore.pm:1022)
    Query: SELECT * FROM options WHERE `key` IN ('enable_perfdata_sync', 'enable_logs_sync', 'centcore_cmd_timeout', 'enable_broker_stats')

**Comment by garnier-quentin** [comment] 2016-08-12 09:30
I think It comes from centcore and the system pipe limits. It has been fixed in centreon 2.7.x.

**Closed** 2016-09-15 13:01 UTC
Labels: Kind/Bug
